spring.application.name=ms-administracion-archivos
server.port=8080

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=INFO
logging.level.io.awspring.cloud=INFO

# Configuracion EFS
efs.path=${EFS_PATH:/app/efs}

# Configuracion S3 y aplicacion
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.s3.enabled=true
app.s3-bucket=${S3_BUCKET:ms-guias-bucket}

# Tamanio maximo de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
